In [2]:
from sklearn.model_selection import StratifiedKFold

from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#from sklearn.decomposition import *
from sklearn.metrics import confusion_matrix

# fix random seed for reproducibility
seed=7
np.random.seed(seed)

In [3]:
# load pima indians dataset
dataset = pd.read_csv("D:/Cours Dauphine/S2/AFD/projet/codeSource/train_cap2018.csv", sep=",")
# split into input (X) and output (Y) variables
scaler = StandardScaler()
X=dataset.iloc[:,1:59].astype(float)
Y=dataset.iloc[:,59]


X, X_test, Y, Y_test = train_test_split(X, Y)
w = np.isnan(X)
X[w] = 0#X.mean() à changer
w2= np.isnan(X_test)
X_test[w2] = 0

#Normalisation 

scaler.fit(X)
StandardScaler(copy=True, with_mean=True, with_std=True)

# Now apply the transformations to the data:
X = scaler.transform(X)
X_test = scaler.transform(X_test)


In [5]:

encoder = LabelEncoder()
encoder.fit(Y)
#converti le Y de chaine de caractères à numérique
Y_numerique = encoder.transform(Y)

print(Y_numerique)
# convert integers to dummy variables (i.e. one hot encoded)
y_encode_binaire = np_utils.to_categorical(Y_numerique)#6

#encoder Y_test
#Pour encoder Y
encoder = LabelEncoder()
encoder.fit(Y_test)
#converti le Y de chaine de caractères à numérique
Y_test_numerique = encoder.transform(Y_test)

print(Y_test_numerique)
# convert integers to dummy variables (i.e. one hot encoded)
y_test_encode_binaire = np_utils.to_categorical(Y_test_numerique)#6

print(y_test_encode_binaire)

[2 2 0 ..., 1 0 0]
[0 0 0 ..., 0 4 0]
[[ 1.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 ..., 
 [ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.]]


In [6]:
#KNN
knn = KNeighborsClassifier()
knn.fit(X, Y_numerique)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X, Y_numerique)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, Y_test_numerique)))

Accuracy of K-NN classifier on training set: 0.82
Accuracy of K-NN classifier on test set: 0.75


In [7]:
svm = SVC()
svm.fit(X,Y_numerique)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X, Y_numerique)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, Y_test_numerique)))

Accuracy of SVM classifier on training set: 0.80
Accuracy of SVM classifier on test set: 0.79


In [8]:
#arbre de décision
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X,Y_numerique)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X,Y_numerique)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test,Y_test_numerique)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.72
