In [52]:
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from keras.optimizers import SGD
import matplotlib.pyplot as plt
from keras import *
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import *
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import seaborn as sns
import matplotlib.pyplot as plt
from keras.metrics import mse, mae, mape
from keras import backend as K
import logging


# fix random seed for reproducibility
np.random.seed(7)
var_w=lambda shape: initializers.RandomUniform(-0.5,0.5)

In [53]:
# load pima indians dataset
dataset = pd.read_csv("/Users/malush/Documents/projet AFD 2018/AFD/train_cap2018.csv", sep=",")
# split into input (X) and output (Y) variables
scaler = StandardScaler()
X=dataset.iloc[:,1:59].astype(float)
Y=dataset.iloc[:,59]


X, X_test, Y, Y_test = train_test_split(X, Y)
w = np.isnan(X)
X[w] = 0#X.mean() à changer
w2= np.isnan(X_test)
X_test[w2] = 0

#Normalisation 

scaler.fit(X)
StandardScaler(copy=True, with_mean=True, with_std=True)

# Now apply the transformations to the data:
X = scaler.transform(X)
X_test = scaler.transform(X_test)

In [54]:
#Pour encoder Y
encoder = LabelEncoder()
encoder.fit(Y)
#converti le Y de chaine de caractères à numérique
Y_numerique = encoder.transform(Y)

print(Y_numerique)
# convert integers to dummy variables (i.e. one hot encoded)
y_encode_binaire = np_utils.to_categorical(Y_numerique)#6

#encoder Y_test
#Pour encoder Y
encoder = LabelEncoder()
encoder.fit(Y_test)
#converti le Y de chaine de caractères à numérique
Y_test_numerique = encoder.transform(Y_test)

print(Y_test_numerique)
# convert integers to dummy variables (i.e. one hot encoded)
y_test_encode_binaire = np_utils.to_categorical(Y_test_numerique)#6

[2 2 0 ... 1 0 0]
[0 0 0 ... 0 4 0]


In [60]:

LDA = LinearDiscriminantAnalysis()
LDA.fit(X, Y_numerique)


#print(LDA.score(X, Y_numerique))

print('Accuracy of LDA classifier on training set: {:.2f}'
     .format(LDA.score(X, Y_numerique)))
print('Accuracy of LDA classifier on test set: {:.2f}'
     .format(LDA.score(X_test, Y_test_numerique)))

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)
pred=LDA.predict(X_test)
print(pred)

classes = encoder.inverse_transform(pred)



print(classes)
#sns.countplot(classes,label="Count")
#plt.show()
tf_session = K.get_session()
logger = logging.getLogger("nom_programme")
Y_test_numerique = Y_test_numerique.astype(np.float32).reshape((-1,1))
mse = metrics.mean_squared_error(Y_test_numerique, pred)
mae = metrics.mean_absolute_error(Y_test_numerique, pred)
mape = metrics.mean_absolute_percentage_error(Y_test_numerique, pred)
#a = mse(Y_test_numerique, pred)
##c = mape(Y_test_numerique, pred)
#f = K.function([], [a,b,c])
#print ('backend result: mse={}, mae={}, mape={}'.format(*f([])))
logger.info('mse=%f' % (mse.eval(session=tf_session)))

/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Accuracy of LDA classifier on training set: 0.73
Accuracy of LDA classifier on test set: 0.73
[0 0 0 ... 0 3 0]
['A1' 'A1' 'A1' ... 'A1' 'B2' 'A1']


ValueError: GraphDef cannot be larger than 2GB.